:ssl: true
:timeout: 100
:port: Rails.application.secrets.rfm_port
:host: Rails.application.secrets.rfm_host
# :account_name: "Users"
# :account_name: "csavoie"
# :password: "Verm!ce11e"
:account_name: Rails.application.secrets.rfm_account_name
:password: Rails.application.secrets.rfm_password
# :database: "MyTest"
:database: Rails.application.secrets.rfm_database
:log_actions: true
:log_responses: true